//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadarView.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LKCM")]
        public string AirportSelected {
            get {
                return ((string)(this["AirportSelected"]));
            }
            set {
                this["AirportSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("445350")]
        public string OsnUserName {
            get {
                return ((string)(this["OsnUserName"]));
            }
            set {
                this["OsnUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("qwert")]
        public string OsnPassword {
            get {
                return ((string)(this["OsnPassword"]));
            }
            set {
                this["OsnPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OgnEnabled {
            get {
                return ((bool)(this["OgnEnabled"]));
            }
            set {
                this["OgnEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OsnEnabled {
            get {
                return ((bool)(this["OsnEnabled"]));
            }
            set {
                this["OsnEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Knots")]
        public string SpeedUnit {
            get {
                return ((string)(this["SpeedUnit"]));
            }
            set {
                this["SpeedUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFF")]
        public string ActiveAirspaceColor {
            get {
                return ((string)(this["ActiveAirspaceColor"]));
            }
            set {
                this["ActiveAirspaceColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#003073")]
        public string BackgroundColor {
            get {
                return ((string)(this["BackgroundColor"]));
            }
            set {
                this["BackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#808080\t")]
        public string AircraftOnGroundColor {
            get {
                return ((string)(this["AircraftOnGroundColor"]));
            }
            set {
                this["AircraftOnGroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#87CEEB")]
        public string AircraftInAirColor {
            get {
                return ((string)(this["AircraftInAirColor"]));
            }
            set {
                this["AircraftInAirColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#F0F0F0")]
        public string AircraftSelectedColor {
            get {
                return ((string)(this["AircraftSelectedColor"]));
            }
            set {
                this["AircraftSelectedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00FF00")]
        public string AircraftNotice1Color {
            get {
                return ((string)(this["AircraftNotice1Color"]));
            }
            set {
                this["AircraftNotice1Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFA500")]
        public string AircraftNotice2Color {
            get {
                return ((string)(this["AircraftNotice2Color"]));
            }
            set {
                this["AircraftNotice2Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF00")]
        public string AircraftAlert1Color {
            get {
                return ((string)(this["AircraftAlert1Color"]));
            }
            set {
                this["AircraftAlert1Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://open.mapquestapi.com/staticmap/v4/getmap?key={0}&size={1},{2}&zoom={3}&ce" +
            "nter={4},{5}")]
        public string MapSourceUrl {
            get {
                return ((string)(this["MapSourceUrl"]));
            }
            set {
                this["MapSourceUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BPTfGFMqU5REeyC5R3I8rYGUXGmFpy7Z")]
        public string MapSourceApiKey {
            get {
                return ((string)(this["MapSourceApiKey"]));
            }
            set {
                this["MapSourceApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public int MapDownloadResolution {
            get {
                return ((int)(this["MapDownloadResolution"]));
            }
            set {
                this["MapDownloadResolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#505050")]
        public string MapColor {
            get {
                return ((string)(this["MapColor"]));
            }
            set {
                this["MapColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("49.61849 15.97027 48.8549 17.13973")]
        public string MonitoredArea {
            get {
                return ((string)(this["MonitoredArea"]));
            }
            set {
                this["MonitoredArea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11000")]
        public int AfisStripUdpPort {
            get {
                return ((int)(this["AfisStripUdpPort"]));
            }
            set {
                this["AfisStripUdpPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int PrecipitationRadarOpacity {
            get {
                return ((int)(this["PrecipitationRadarOpacity"]));
            }
            set {
                this["PrecipitationRadarOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFF88")]
        public string MonitoredAreaRectColor {
            get {
                return ((string)(this["MonitoredAreaRectColor"]));
            }
            set {
                this["MonitoredAreaRectColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FAFAFA")]
        public string AirportColor {
            get {
                return ((string)(this["AirportColor"]));
            }
            set {
                this["AirportColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int MeteoDataUpdateIntervalSeconds {
            get {
                return ((int)(this["MeteoDataUpdateIntervalSeconds"]));
            }
            set {
                this["MeteoDataUpdateIntervalSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int PrecipitationRadarUpdateIntervalSeconds {
            get {
                return ((int)(this["PrecipitationRadarUpdateIntervalSeconds"]));
            }
            set {
                this["PrecipitationRadarUpdateIntervalSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.openweathermap.org/data/2.5/weather?lat={0}&lon={1}&appid={2}")]
        public string MeteoDataUrl {
            get {
                return ((string)(this["MeteoDataUrl"]));
            }
            set {
                this["MeteoDataUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4376044d7f47ce4814566d60544dc6dd ")]
        public string MeteoDataApiKey {
            get {
                return ((string)(this["MeteoDataApiKey"]));
            }
            set {
                this["MeteoDataApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("51.447900 11.288265 48.061492 19.608423")]
        public string PrecipitationRadarArea {
            get {
                return ((string)(this["PrecipitationRadarArea"]));
            }
            set {
                this["PrecipitationRadarArea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://{0}.meteor.androworks.org/feed")]
        public string PrecipitationRadarDateTimeUrl {
            get {
                return ((string)(this["PrecipitationRadarDateTimeUrl"]));
            }
            set {
                this["PrecipitationRadarDateTimeUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("85")]
        public int MonitoredAreaAutoSetSizeKilometers {
            get {
                return ((int)(this["MonitoredAreaAutoSetSizeKilometers"]));
            }
            set {
                this["MonitoredAreaAutoSetSizeKilometers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int ViewRenderFPS {
            get {
                return ((int)(this["ViewRenderFPS"]));
            }
            set {
                this["ViewRenderFPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int AircraftTrailDotsMaxCount {
            get {
                return ((int)(this["AircraftTrailDotsMaxCount"]));
            }
            set {
                this["AircraftTrailDotsMaxCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int AircraftTrailDotsStandartCount {
            get {
                return ((int)(this["AircraftTrailDotsStandartCount"]));
            }
            set {
                this["AircraftTrailDotsStandartCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public float ViewZoomLevelChange {
            get {
                return ((float)(this["ViewZoomLevelChange"]));
            }
            set {
                this["ViewZoomLevelChange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int RenderUpdateInterval {
            get {
                return ((int)(this["RenderUpdateInterval"]));
            }
            set {
                this["RenderUpdateInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int AircraftLabelAltitudeDigitsCount {
            get {
                return ((int)(this["AircraftLabelAltitudeDigitsCount"]));
            }
            set {
                this["AircraftLabelAltitudeDigitsCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int AircraftLabelGroundSpeedDigitsCount {
            get {
                return ((int)(this["AircraftLabelGroundSpeedDigitsCount"]));
            }
            set {
                this["AircraftLabelGroundSpeedDigitsCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int AircraftLabelAltSpeedSpacesCount {
            get {
                return ((int)(this["AircraftLabelAltSpeedSpacesCount"]));
            }
            set {
                this["AircraftLabelAltSpeedSpacesCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int AircraftLabelColumnSpacesCount {
            get {
                return ((int)(this["AircraftLabelColumnSpacesCount"]));
            }
            set {
                this["AircraftLabelColumnSpacesCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PrecipitationRadarIsVisible {
            get {
                return ((bool)(this["PrecipitationRadarIsVisible"]));
            }
            set {
                this["PrecipitationRadarIsVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MeteoDataAreVisible {
            get {
                return ((bool)(this["MeteoDataAreVisible"]));
            }
            set {
                this["MeteoDataAreVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LocalTimeZone {
            get {
                return ((bool)(this["LocalTimeZone"]));
            }
            set {
                this["LocalTimeZone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.5")]
        public float AirportRunwayThickness {
            get {
                return ((float)(this["AirportRunwayThickness"]));
            }
            set {
                this["AirportRunwayThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2147483647")]
        public int ViewMaxAltitude {
            get {
                return ((int)(this["ViewMaxAltitude"]));
            }
            set {
                this["ViewMaxAltitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://{0}.meteor.androworks.org/images/radar/image-{1}")]
        public string PrecipitationRadarImagesServerUrl {
            get {
                return ((string)(this["PrecipitationRadarImagesServerUrl"]));
            }
            set {
                this["PrecipitationRadarImagesServerUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public float PredictorVerticalSpeedThreshold {
            get {
                return ((float)(this["PredictorVerticalSpeedThreshold"]));
            }
            set {
                this["PredictorVerticalSpeedThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int AircraftSpeedVectorTimeLengthSeconds {
            get {
                return ((int)(this["AircraftSpeedVectorTimeLengthSeconds"]));
            }
            set {
                this["AircraftSpeedVectorTimeLengthSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int PredictorVerticalSpeedTimeDiff {
            get {
                return ((int)(this["PredictorVerticalSpeedTimeDiff"]));
            }
            set {
                this["PredictorVerticalSpeedTimeDiff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public int AircraftRealFixTimeout {
            get {
                return ((int)(this["AircraftRealFixTimeout"]));
            }
            set {
                this["AircraftRealFixTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DataSourceLogsEnabled {
            get {
                return ((bool)(this["DataSourceLogsEnabled"]));
            }
            set {
                this["DataSourceLogsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int AircraftRealFixCount {
            get {
                return ((int)(this["AircraftRealFixCount"]));
            }
            set {
                this["AircraftRealFixCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>OGN</string>\r\n  <string>OSN</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DataSourcePriority {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DataSourcePriority"]));
            }
            set {
                this["DataSourcePriority"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int MaxRealFixAgeSeconds {
            get {
                return ((int)(this["MaxRealFixAgeSeconds"]));
            }
            set {
                this["MaxRealFixAgeSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int AircraftRealFixTextureSize {
            get {
                return ((int)(this["AircraftRealFixTextureSize"]));
            }
            set {
                this["AircraftRealFixTextureSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int AircraftTrailDotTextureSize {
            get {
                return ((int)(this["AircraftTrailDotTextureSize"]));
            }
            set {
                this["AircraftTrailDotTextureSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int AircraftTargetTextureSize {
            get {
                return ((int)(this["AircraftTargetTextureSize"]));
            }
            set {
                this["AircraftTargetTextureSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int AircraftMaxFadingTime {
            get {
                return ((int)(this["AircraftMaxFadingTime"]));
            }
            set {
                this["AircraftMaxFadingTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public float PredictorSquawkAreaThreshold {
            get {
                return ((float)(this["PredictorSquawkAreaThreshold"]));
            }
            set {
                this["PredictorSquawkAreaThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"mapLayers\":[{\"name\":\"Základní mapa\",\"imageName\":\"BasicMap\",\"isVisible\":false,\"b" +
            "oundingBoxes\":{\"9\":\"51.85402 12.43535 46.47334 20.675\",\"11\":\"49.90481 15.52526 4" +
            "8.5598 17.58519\",\"13\":\"49.40472 16.29773 49.06847 16.81272\"}}]}")]
        public string MapConfig {
            get {
                return ((string)(this["MapConfig"]));
            }
            set {
                this["MapConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yyyyMMdd.HHmm")]
        public string PrecipitationRadarResourceTimestampFormat {
            get {
                return ((string)(this["PrecipitationRadarResourceTimestampFormat"]));
            }
            set {
                this["PrecipitationRadarResourceTimestampFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NtpSynchronizationOffsetPanelIsVisible {
            get {
                return ((bool)(this["NtpSynchronizationOffsetPanelIsVisible"]));
            }
            set {
                this["NtpSynchronizationOffsetPanelIsVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int AircraftTrailDotsUpdateIntervalMiliseconds {
            get {
                return ((int)(this["AircraftTrailDotsUpdateIntervalMiliseconds"]));
            }
            set {
                this["AircraftTrailDotsUpdateIntervalMiliseconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AirportsAreVisible {
            get {
                return ((bool)(this["AirportsAreVisible"]));
            }
            set {
                this["AirportsAreVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NtpSynchronizationEnabled {
            get {
                return ((bool)(this["NtpSynchronizationEnabled"]));
            }
            set {
                this["NtpSynchronizationEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"		{""A"":""#1E90FF"",""B"":""#1E90FF"", ""C"":""#1E90FF"", ""CTR"":""#1E90FF"", ""D"":""#1E90FF"", ""Danger"":""#1E90FF"", ""E"":""#1E90FF"", ""F"":""#1E90FF"", ""G"":""#1E90FF"", ""Gliding"":""#1E90FF"", ""OTH"":""#1E90FF"", ""Restricted"":""#E68523"", ""TMA"":""#1E90FF"", ""TMZ"":""#1E90FF"", ""Wave"":""#1E90FF"", ""Prohibited"":""#DD5183"", ""FIR"":""#1E90FF"", ""UIR"":""#1E90FF"", ""RMZ"":""#1E90FF"", ""Other"":""#1E90FF""}")]
        public string AirspaceCategoriesColors {
            get {
                return ((string)(this["AirspaceCategoriesColors"]));
            }
            set {
                this["AirspaceCategoriesColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pool.ntp.org")]
        public string NtpSynchronizationServerUrl {
            get {
                return ((string)(this["NtpSynchronizationServerUrl"]));
            }
            set {
                this["NtpSynchronizationServerUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int NtpSynchronizationIntervalSeconds {
            get {
                return ((int)(this["NtpSynchronizationIntervalSeconds"]));
            }
            set {
                this["NtpSynchronizationIntervalSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8000")]
        public int AirportAreaSizeMeters {
            get {
                return ((int)(this["AirportAreaSizeMeters"]));
            }
            set {
                this["AirportAreaSizeMeters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int PredictorMaxGroundSpeedForOnGroundDetection {
            get {
                return ((int)(this["PredictorMaxGroundSpeedForOnGroundDetection"]));
            }
            set {
                this["PredictorMaxGroundSpeedForOnGroundDetection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("130")]
        public int PredictorAltitudeThresholdForOnGroundDetection {
            get {
                return ((int)(this["PredictorAltitudeThresholdForOnGroundDetection"]));
            }
            set {
                this["PredictorAltitudeThresholdForOnGroundDetection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int PredictorMaxPredictedSeconds {
            get {
                return ((int)(this["PredictorMaxPredictedSeconds"]));
            }
            set {
                this["PredictorMaxPredictedSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int PredictorMinTimeIntervaForPredictionSeconds {
            get {
                return ((int)(this["PredictorMinTimeIntervaForPredictionSeconds"]));
            }
            set {
                this["PredictorMinTimeIntervaForPredictionSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int PredictorMinFixCountForLinearRegresion {
            get {
                return ((int)(this["PredictorMinFixCountForLinearRegresion"]));
            }
            set {
                this["PredictorMinFixCountForLinearRegresion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AircraftRealFixesAreVisible {
            get {
                return ((bool)(this["AircraftRealFixesAreVisible"]));
            }
            set {
                this["AircraftRealFixesAreVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.5")]
        public float MeasuringLineThickness {
            get {
                return ((float)(this["MeasuringLineThickness"]));
            }
            set {
                this["MeasuringLineThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FEF975")]
        public string MeasuringLineColor {
            get {
                return ((string)(this["MeasuringLineColor"]));
            }
            set {
                this["MeasuringLineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.25")]
        public float PredictorMaxRadiusForCirleFitting {
            get {
                return ((float)(this["PredictorMaxRadiusForCirleFitting"]));
            }
            set {
                this["PredictorMaxRadiusForCirleFitting"] = value;
            }
        }
    }
}
